<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />	
	<title><?php echo $api->getTitulo() ?> - Creator Api</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- stylesheets -->
	<link rel="stylesheet" type="text/css" href="css/compiled/theme.css" />
	<link rel="stylesheet" type="text/css" href="css/vendor/animate.css" />
	<link rel="stylesheet" type="text/css" href="css/vendor/highlight.default.css" />

	<!-- javascript -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script src="js/bootstrap/bootstrap.min.js"></script>
	<script src="js/theme.js"></script>
	<script src="js/vendor/highlight.min.js"></script>

	<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body id="docs" data-spy="scroll" data-target="#guide">
	<div id="guide">
		<h1 class="logo">
			<a href="index.html"><?php echo $api->getTitulo() ?></a>
		</h1>
		<ul class="menu nav">
            <li style="color: #AEAEAE; padding-left: 10px;">API</li>
            <li>
			  	<a href="#intro">Introduction</a>
			</li>
			<li>
			  	<a href="#auth">Authentication</a>
			</li>
			<li>
			  	<a href="#errors">Errors</a>
			</li>
			<li style="color: #AEAEAE; padding-left: 10px;">Resources</li>
			<?php 
			foreach ($recursos as $recurso):
			
				if ($recurso->getGet() == 'INATIVO' && $recurso->getPost() == 'INATIVO' && $recurso->getPut() == 'INATIVO' && $recurso->getDelete() == 'INATIVO')
					continue;
			
				$hash = '#'.$recurso->getId();
			?>
			<li>
				<a href="<?php echo $hash ?>"><?php echo $recurso->getResource() ?></a>
				<ul class="nav">
					<?php 
					if ($recurso->getGet() == 'ATIVO'):
					?>
				    <li><a href="<?php echo $hash.'-retrieve-list' ?>"><span class="label label-primary">Retrieve list</span></a></li>
				    <li><a href="<?php echo $hash.'-retrieve' ?>"><span class="label label-info">Retrieve one</span></a></li>
				    <?php
				    endif;
				    
				    if ($recurso->getPost() == 'ATIVO'):
				    ?>
				    <li><a href="<?php echo $hash.'-create' ?>"><span class="label label-success">Create</span></a></li>
				    <?php 
				    endif;
				    
				    if ($recurso->getPut() == 'ATIVO'):
				    ?>
				    <li><a href="<?php echo $hash.'-update' ?>"><span class="label label-warning">Update</span></a></li>
				    <?php 
				    endif;
				    
				    if ($recurso->getDelete() == 'ATIVO'):
				    ?>
				    <li><a href="<?php echo $hash.'-delete' ?>"><span class="label label-danger">Delete</span></a></li>
				    <?php 
				    endif;
				    ?>
			  	</ul>
			</li>
			<?php 
			endforeach;
			?>
		</ul>
	</div>

	<div id="api-docs">
		<div id="methods">
			<div class="languages">
				<a class="language selected" data-lang="php" href="#">PHP</a>
				<a class="language" data-lang="ruby" href="#">Ruby</a>
				<a class="language" data-lang="python" href="#">Python</a>
			</div>
			<div class="method" id="intro">
				<div class="method-section clearfix">
					<div class="method-description">
						<h3>Introduction</h3>
						<p><?php echo nl2br($this->escapehtml($api->getDescricao())) ?></p>
					</div>
					<div class="method-example">
						<pre>
<code class="php">
# Include ZF2
# http://framework.zend.com/manual/2.0/en/modules/zend.http.client.html
$request = new \Zend\Http\Client();
$request->setHeaders(array(
	'Accept' => 'application/json', /* or 'application/xml' */
	'X-Api-Token' => $token /* http://www.criadorapi.com/user-token */
));
</code>
						</pre>
					</div>
				</div>
			</div>
			<div class="method" id="auth">
				<div class="method-section clearfix">
					<div class="method-description">
						<h3>Authentication</h3>
						<p>
							Nas requisições é obrigatório o envio do cabeçalho <a href="http://en.wikipedia.org/wiki/Basic_access_authentication" target="_blank">"Authorization"</a>, siga as etapas abaixo para realizar o envio:
						</p>
						<ol style="font-size: 13px; color: #666; line-height: 21px; margin-bottom: 20px;">
							<li>Construa uma string no formato email:senha;</li>
							<li>Codifique a string com <a href="http://en.wikipedia.org/wiki/Base64" target="_blank">Base64</a>;</li>
							<li>Forneça um cabeçalho "Authorization" com conteúdo "Basic" seguido pela seqüência codificada, por exemplo, "Authorization: Basic ZW1haWw6c2VuaGE=";</li>
						</ol>
					</div>
					<div class="method-example">
						<pre>
							<code class="php">$request->setAuth($email , $password);</code>
						</pre>
					</div>
				</div>
			</div>
			<div class="method" id="errors">
				<div class="method-section clearfix">
					<div class="method-description">
						<h3>Errors</h3>
						<p>
						</p>
						<div class="info">
							<h4>Attributes</h4>
							<div class="field clearfix">
								<div class="key">status:</div>
								<div class="desc">
									<strong>"error"</strong>
									Code of the error
								</div>
							</div>
							<div class="field clearfix">
								<div class="key">message:</div>
								<div class="desc">
									<strong>string</strong>
									A complete message with details about the error to show users.
								</div>
							</div>
							<div class="field clearfix">
								<div class="key">code:</div>
								<div class="desc">
									<strong>int</strong>
									Code of the error
								</div>
							</div>
						</div>
					</div>
					
					<div class="method-example">
<pre>
<code class="json always-visible">
{
	status: "error",
		result: {
			message: "Message",
			code: 4001
		}
}
</code>
<code class="http always-visible">200 OK - Everything worked.

400 Bad Request - The request was badly built

401 Unauthorized - Some other message

402 Request Failed - The request failed

404 Not Found - Doesn't exist

500, 502, 503, 504 Server errors
</code>
</pre>
					</div>
				</div>
			</div>
			
			
			<?php 
			foreach ($recursos as $recurso):
				//$recurso = new \Application\Model\Recurso();
				if ($recurso->getGet() == 'INATIVO' && $recurso->getPost() == 'INATIVO' && $recurso->getPut() == 'INATIVO' && $recurso->getDelete() == 'INATIVO')
					continue;
			
				$cache = (int)$api->getCache();
				if (!empty($recurso->getCache()))
					$cache = (int)$recurso->getCache();
				
				$nome_recuros = $recurso->getResource();
				$hash = $recurso->getId();
				$url_recurso = $this->url('host-api/resource', array('api' => $api->getUrl(), 'resource' => $nome_recuros));
			
				$colunas = $recurso->getColunaCollection();
				$colunas_select = array();
				$colunas_insert = array();
				$colunas_validators = array();
				foreach ($colunas as $coluna) {
					//$coluna = new \Application\Model\Coluna();
					
					
					$nome = $coluna->getNome();
					$tipo = $coluna->getTipo();
					if ($coluna->getSelect() == 'SIM') {
						$colunas_select[] = array(
							'nome' => $nome,
							'tipo' => $tipo,
						);
					}
					if ($coluna->getInsert() == 'SIM') {
						$colunas_insert[] = array(
							'nome' => $nome,
							'tipo' => $tipo,
						);
						$coluna_validators = $coluna->getColunaValidadorCollection()->toArray();
						if (!empty($coluna_validators))
							$colunas_validators[$nome] = $coluna_validators; 
					}
				}
				
				$example_select = '';
				$fields_select = '';
				foreach ($colunas_select as $col):
					$example_select .= '&#09;&#09;&#09;&#09;&#09;'.$col['nome'].': null,<br>';
					$fields_select .= '<div class="field clearfix">
											<div class="key">'.$col['nome'].':</div>
											<div class="desc">
												<strong>'.$col['tipo'].'</strong>
											</div>
										</div>';
				endforeach;

				$example_insert = '';
				$fields_insert = '';
				foreach ($colunas_insert as $col):
					$example_insert .= "&#09;&#09;&#09;'{$col['nome']}' => null,<br>";
					$fields_insert .= '<div class="field clearfix">
											<div class="key">'.$col['nome'].':</div>
											<div class="desc">
												<strong>'.$col['tipo'].'</strong>
											</div>
										</div>';
				endforeach;
			?>
			<div class="method" id="<?php echo $hash ?>">
				<div class="method-section clearfix" style="/*background-color: #F4F8FA; padding-top: 0; margin-bottom: -50px;*/">
					<div class="method-description">
						<h1><?php echo $nome_recuros ?></h1>
						<p>
							<?php echo $recurso->getDescricao() ?>
						</p>
					</div>
					<div class="method-example">
						<pre>
							<code class="php"></code>
						</pre>
					</div>
				</div>
				<?php 
				if ($recurso->getGet() == 'ATIVO'):
				?>
				<div id="<?php echo $hash.'-retrieve-list' ?>" class="method-section clearfix">
					<div class="method-description">
						<h2>
							<span class="label label-primary">Retrieve list</span> <small><?php echo $nome_recuros ?></small> 
						</h2>
						<div class="info">
							<h4>Fields</h4>
							<?php echo $fields_select ?>
						</div>
					</div>
					<div class="method-example">
						<pre>
<code class="php">
# Request
$request->setMethod('GET');
$request->setUri('<?php echo $url_recurso ?>?page=2&per_page=10');
$response = $request->dispatch();
</code>
<code class="php always-visible">
# Response
# Status code: 200
<?php 
if (!empty($cache))
	echo '# Cache-Control: max-age='.$cache;
?>

{
	status: "success",
	result: {
		first: 1,
		previous: 1,
		current: 2,
		next: 3,
		last: 10,
		_links: {
			first: "<?php echo $url_recurso ?>?page=1&per_page=10",
			previous: "<?php echo $url_recurso ?>?page=1&per_page=10",
			current: "<?php echo $url_recurso ?>?page=2&per_page=10",
			next: "<?php echo $url_recurso ?>?page=3&per_page=10",
			last: "<?php echo $url_recurso ?>?page=10&per_page=10"
		},
		per_page: 10,
		total_itens: 30,
		data: [
			{
<?php echo $example_select ?>
			},
			{
<?php echo $example_select ?>
			}
		]
	}
}
</code>
						</pre>
					</div>
				</div>
				
				<div id="<?php echo $hash.'-retrieve' ?>" class="method-section clearfix">
					<div class="method-description">
						<h2>
							<span class="label label-info">Retrieve one</span> <small><?php echo $nome_recuros ?></small> 
						</h2>
						<div class="info">
							<h4>Fields</h4>
							<?php echo $fields_select ?>
						</div>
					</div>
					<div class="method-example">
						<pre>
<code class="php">
# Request
$request->setMethod('GET');
$request->setUri('<?php echo $url_recurso ?>/{id}');
$response = $request->dispatch();
</code>
<code class="php always-visible">
# Response
# Status code: 200
<?php 
if (!empty($cache))
	echo '# Cache-Control: max-age='.$cache;
?>

{
	status: "success",
	result: {
<?php echo $example_select ?>
	}
}
</code>
						</pre>
					</div>
				</div>
			    <?php
			    endif;
			    
			    if ($recurso->getPost() == 'ATIVO'):
			    ?>
			    <div id="<?php echo $hash.'-create' ?>" class="method-section clearfix">
					<div class="method-description">
						<h2>
							<span class="label label-success">Create</span> <small><?php echo $nome_recuros ?></small> 
						</h2>
						<div class="info">
							<h4>Fields</h4>
							<?php echo $fields_insert ?>
						</div>
						<?php 
						if (!empty($colunas_validators)):
						?>
						<div class="info">
							<h4>Validators</h4>
							<?php 
							foreach ($colunas_validators as $col => $validators):
							?>
							<div class="field clearfix">
								<div class="key"><?php echo $col ?>:</div>
								<?php 
								foreach ($validators as $validator):
								?>
								<div class="desc">
									<strong><?php echo $validator->getValidador()->getNome() ?></strong>
									<?php 
									$params = unserialize($validator->getParams());
									if (!empty($params))
										foreach ($params as $k => $v)
											echo $k.': '.$v.'<br>';
									?>
								</div>
								<?php
								endforeach; 
								?>
							</div>
							<?php 
							endforeach;
							?>
						</div>
						<?php 
						endif;
						?>
					</div>
					<div class="method-example">
						<pre>
<code class="php">
# Request
$request->setMethod('POST');
$request->setHeaders(array('Content-Type' => 'application/json'));
$request->setUri('<?php echo $url_recurso ?>');
$request->setRawBody(json_encode(array(
<?php echo $example_insert?>
)));
$response = $request->dispatch();
</code>
<code class="php always-visible">
# Response
# Status code: 201
{
	status: "success",
	result: {
		message: "Successfully added",
		link: "http:<?php echo $url_recurso ?>/{id}"
	}
}
</code>
						</pre>
					</div>
				</div>
			    <?php 
			    endif;
			    
			    if ($recurso->getPut() == 'ATIVO'):
			    ?>
			    <div id="<?php echo $hash.'-update' ?>" class="method-section clearfix">
					<div class="method-description">
						<h2>
							<span class="label label-warning">Update</span> <small><?php echo $nome_recuros ?></small> 
						</h2>
						<div class="info">
							<h4>Fields</h4>
							<?php echo $fields_insert ?>
						</div>
						<?php 
						if (!empty($colunas_validators)):
						?>
						<div class="info">
							<h4>Validators</h4>
							<?php 
							foreach ($colunas_validators as $col => $validators):
							?>
							<div class="field clearfix">
								<div class="key"><?php echo $col ?>:</div>
								<?php 
								foreach ($validators as $validator):
								?>
								<div class="desc">
									<strong><?php echo $validator->getValidador()->getNome() ?></strong>
									<?php 
									$params = unserialize($validator->getParams());
									if (!empty($params))
										foreach ($params as $k => $v)
											echo $k.': '.$v.'<br>';
									?>
								</div>
								<?php
								endforeach; 
								?>
							</div>
							<?php 
							endforeach;
							?>
						</div>
						<?php 
						endif;
						?>
					</div>
					<div class="method-example">
						<pre>
<code class="php">
# Request
$request->setMethod('PUT');
$request->setHeaders(array('Content-Type' => 'application/json'));
$request->setUri('<?php echo $url_recurso ?>/{id}');
$request->setRawBody(json_encode(array(
<?php echo $example_insert?>
)));
$response = $request->dispatch();
</code>
<code class="php always-visible">
# Response
# Status code: 200
{
	status: "success",
	result: {
		message: "Successfully changed"
	}
}
</code>
						</pre>
					</div>
				</div>
			    <?php 
			    endif;
			    
			    if ($recurso->getDelete() == 'ATIVO'):
			    ?>
			    <div id="<?php echo $hash.'-delete' ?>" class="method-section clearfix">
					<div class="method-description">
						<h2>
							<span class="label label-danger">Delete</span> <small><?php echo $nome_recuros ?></small> 
						</h2>
						<div class="info">
						</div>
					</div>
					<div class="method-example">
						<pre>
<code class="php">
# Request
$request->setMethod('DELETE');
$request->setUri('<?php echo $url_recurso ?>/{id}');
$response = $request->dispatch();
</code>
<code class="php always-visible">
# Response
# Status code: 200
{
	status: "success",
	result: {
		message: "Deleted successfully"
	}
}
</code>
						</pre>
					</div>
				</div>
			    
			    <?php 
			    endif;
			    ?>
				
			</div>
			<?php 
			endforeach;
			?>
		</div>
	</div>

	<script type="text/javascript">
		$(function () {
			hljs.configure({
			  tabReplace: '  ',
			  classPrefix: ''
			})
			hljs.initHighlightingOnLoad();


			// language toggle
			var $languages = $(".languages .language");
			$languages.click(function (e) {
				e.preventDefault();
				var lang = $(this).data("lang");
				$languages.removeClass("selected");
				$(this).addClass("selected");

				$("pre code").hide();
				$("pre code." + lang).css("display", "block");
			});

			$('.languages .language.selected').trigger( "click" );
		});
	</script>
</body>
</html>