<span class="label label-info">Recurso: <?php echo $this->resource->getResource() ?></span>
<br><br>
<table class="table table-striped">
	<thead>
		<tr>
			<th style="width: 30%;">Campo</th>
			<th style="width: 30%;">Tipo</th>
			<th style="width: 40%;">Ações</th>
        </tr>
	</thead>
	<tbody>
	<?php
	foreach ($this->resource->getColunaCollection() as $coluna):
	?>
	<tr>
		<td><?php echo $coluna->getNome() ?></td>
		<td><?php echo $coluna->getTipo() ?></td>
		<td>
			<?php 
			if ($this->resource->getTipo() == 'TABLE'):
			?>
				<button type="button" class="btn btn-default btn-sm" onclick="showModalValidators('<?php echo $resource->getId() ?>', '<?php echo $coluna->getId() ?>')"><i class="fa fa-check-square-o fa-fw"></i> Validadores</button>
			<?php 
			endif;
			?>
			<button type="button" class="btn btn-default btn-sm" onclick="showModalEditCols('<?php echo $coluna->getId() ?>')"><i class="fa fa-pencil fa-fw"></i> Opções</button>
		</td>
	</tr>
	<?php 
	endforeach;
	?>
	</tbody>
</table>
