<?php echo $this->doctype() ?>
<html class="bg1">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />	
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	
<!-- stylesheets -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/css/compiled/theme.css')
                ->appendStylesheet($this->basePath() . '/css/vendor/brankic.css')
                ->appendStylesheet($this->basePath() . '/css/vendor/ionicons.min.css')
                ->appendStylesheet($this->basePath() . '/css/vendor/font-awesome.min.css') 
?>

<!-- javascript -->
<?php echo $this->headScript()
                ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js')
                ->appendFile($this->basePath() . 'js/bootstrap/bootstrap.min.js') 
                ->appendFile($this->basePath() . 'js/theme.js') 
                ->appendFile('http://html5shim.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
?>
	
</head>
<body >

    <?php 
    /*
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="<?php echo $this->url('site/index') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="<?php echo $this->url('site/index') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
    */
    ?>
    
	<?php echo $this->content; ?>
	
    <?php echo $this->inlineScript() ?>

    <?php 
    /*echo '<pre>';
    print_r($this->flashmessenger()->getMessages());
    echo '</pre>';*/ 
    
//     echo '<pre>';
//     print_r($flashMessenger = $this->flashMessenger());
//     echo '</pre>';
    /*
    
    <div class="signup-switcher">
    	<a href="#" class="active" data-class="clear">
    		<i class="fa fa-check"></i>
    		Clear
    	</a>
    	<a href="#" data-class="">
    		<i class="fa fa-check"></i>
    		Dark
    	</a>
    </div>
	<script type="text/javascript">
		$(function () {
			var $switcher = $(".signup-switcher a");
			$switcher.click(function (e) {
				e.preventDefault();
				$switcher.removeClass("active");
				$(this).addClass("active");
				$("body").attr("class", $(this).data("class"));
			});
		});
	</script>
	*/
    ?>
</body>
</html>

