
<div id="content">
    <div class="menubar">
    	<div class="sidebar-toggler visible-xs">
    		<i class="ion-navicon"></i>
    	</div>
    	<div class="page-title">
			Minhas APIs
    	</div>
    	<a  href="<?php echo $this->url('api') ?>" data-pjax class="new-user btn btn-success pull-right"><span>Criar uma nova API</span></a>
    </div>
    <div class="content-wrapper clearfix">
    	 
        <div id="projects">
            <div class="row project-list">
            	<div class="project new">
            		<a href="<?php echo $this->url('api') ?>" data-pjax>
            			<i class="ion-ios7-plus-outline"></i>
            			<span class="info">
            				Criar uma nova API
            			</span>
            		</a>
            	</div>
            	
            	<?php
                foreach ($this->results as $result):
            	?>
            	<div class="project" data-id="<?php echo $result['id'] ?>">
            		<div class="info">
            			<div class="name">
            				<?php echo substr($this->escapehtml($result['titulo']), 0, 50) ?>
            				<?php 
            				if ($result['acesso'] == 'PRIVADO'):
            				?>
							<i class="fa fa-lock" style="color:#D9534F; font-size: 13px;" title="Private"></i>
							<?php 
							else:
							?>
							<i class="fa fa-unlock-alt" style="color:#22B92E; font-size: 13px;" title="Public"></i>
							<?php 
							endif;
							?>
            			</div>
            			<div class="category"><?php echo substr($this->escapehtml($result['descricao']), 0, 200)  ?></div>
            			<?php 
            			//<div class="last-update">Last updated 3 hours ago</div>
            			?>
            		</div>
            		<div class="members">
            			<?php 
            			foreach ($this->api_users($result['id']) as $user):
                            echo $this->gravatar(
                                $user['email'],
                                array('img_size' => 50), 
                                array(
                                    'class' => strtolower($user['permissao']),
                                    'data-toggle' => 'popover',
                                    'data-content' => '<b>'.$user['nome'].'</b><br>@'.$user['username'],
                                    'title' => '',
                                )
                            );    
            			endforeach;
            			?>
            			<a href="#" class="add-more"><i class="fa fa-plus"></i></a>
            			<ul class="menu">
                            <li><a href="<?php echo $this->url('host-api/index', array('api' => $result['url'], 'port' => ':8080')) ?>" target="_blank"><i class="fa fa-code fa-fw"></i>Doc</a></li>
            				<?php 
            				if ($result['permissao'] == 'OWNER' || $result['permissao'] == 'EDIT'):
            				    $param_id = array('id' => $result['id']);
            				?>
            				<li>
            				    <a href="<?php echo $this->url('api', $param_id) ?>" data-pjax><i class="fa fa-pencil fa-fw"></i>Editar</a>
            				</li>
            				<li><a href="<?php echo $this->url('api-share', $param_id) ?>" data-pjax><i class="fa fa-share-alt fa-fw"></i>Compartilhamento</a></li>
            				<li><a href="<?php echo $this->url('api-resources', $param_id) ?>" data-pjax><i class="fa fa-list fa-fw"></i>Recursos</a></li>
            				<?php 
            				endif;
            				?>
            				<?php 
            				if ($result['permissao'] == 'OWNER'):
            				?>
            				<li><a href="#" class="delete-api"><i class="fa fa-trash-o fa-fw"></i> Delete Api</a></li>
            				<?php 
            				endif;
            				?>
            			</ul>
            		</div>
            	</div>
            	<?php 
            	endforeach;
            	?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function () {

	$('.members img').popover({html: true, placement: 'top'});
	var $projects = $(".project");

	$projects.each(function (index, el) {
		var $btn = $(el).find(".add-more");
		var $menu = $btn.siblings(".menu");
		var timeout;

		$btn.click(function (e) { e.preventDefault(); });

		$(el).on("mouseenter", ".add-more, .menu", function () {
			clearTimeout(timeout);
			timeout = null;
			$menu.addClass("active");
		});

		$(el).on("mouseleave", ".add-more, .menu", function () {
			timeout = setTimeout(function () {
				$menu.removeClass("active");
			}, 400);
		});
	});

	$(".delete-api").on('click', function(e) {
		e.preventDefault();

		var elem = $(this);
        var row = elem.closest('div.project');
		var id = row.data('id');

		func_confirm_modal = function() {
    		row.css('background', '#FFE3E3'); 

    		sendAjax({
    			url: "<?php echo $this->url('api', array(), array(), true) ?>/"+id,
    			type: 'DELETE',
    			done: function(result) {
    				row.addClass('bounceOutRight animated'); 
    				setTimeout(function(){row.remove();}, 750);
    			},
    			always: function(result) {
    				row.css('background', '');
    			}
    		});
        };
        showConfirmModal({title: 'Tem certeza de que deseja removar essa API?'});
		
	});

});
</script>