<div id="panel" class="profile">
	<h3>
		Profile settings
	</h3>

	<p class="intro">
		Change your account information, avatar, login credentials, etc.
	</p>
	
	<?php 
	$form->setAttribute('action', $this->url(null, array(), array(), true));
	echo $this->form()->openTag($form);
	?>
	<div class="form-group avatar-field clearfix">
	    <div class="col-sm-3">
	    	<?php 
		    	echo $this->gravatar(
	    			$this->layout()->user->email,
	    			array('img_size' => 128),
	    			array(
    					'class' => 'img-responsive img-circle',
	    			)
		    	);
		    	?>
	    </div>
	    <div class="col-sm-9">
	    	<label>Set up your avatar picture</label><br>
	    	<a href="http://gravatar.com" target="_blank">gravatar.com</a>
	    </div>
  	</div>
  	<?php 
  	echo $this->formCollection($form);
  	?>
	<div class="form-group ">
		<input type="submit" class="btn btn-success btn-lg" value="Salvar" />
	</div>
	<?php 
	echo $this->form()->closeTag();
	?>
</div>
	
<script type="text/javascript">
$(function () {
    $('#form-user-info').validate({
    	rules: {
    		username: {
    			checkURL: true
    		},
    		password: {
				required: false,
				minlength: 5
			}
    	},
    	submitHandler: function(form) {
    		sendAjax({
    			form: $(form),
    			done: function(result) {
            	}
        	});
        	return false;
    	},
    });
});
</script>