<div id="signin">
    <a href="<?php echo $this->url('index') ?>" class="logo">
    	<i class="brankic-pen"></i>
    </a>
    <div class="content">
        <form>
			<div class="fields">
				<strong>Your information</strong>
				<input class="form-control input-lg" type="text" placeholder="Your email" />
			</div>
			<div class="signup">
				<a href="index.html" class="btn btn-success btn-lg">Buscar</a>
			</div>
		</form>
    	
    </div>
    
    <div class="bottom-wrapper">
    	<div class="message">
    		<a href="<?php echo $this->url('login') ?>">Sign in here</a>.
    	</div>
    </div>
    
    
</div>