<div id="signin">
    <a href="<?php echo $this->url('index') ?>" class="logo">
    	<i class="brankic-pen"></i>
    </a>
    
    <h3>Register</h3>
    
    <div class="content">
        <form>
			<div class="fields">
				<strong>Your information</strong>
				<input class="form-control" type="text" placeholder="Your email" />
				<input class="form-control" type="password" placeholder="Password" />
				<input class="form-control" type="password" placeholder="Confirm password" />
			</div>
			<div class="signup">
				<a href="index.html" class="btn btn-success btn-lg">Create my account</a>
			</div>
		</form>
    	
    </div>
    
    <div class="bottom-wrapper">
    	<div class="message">
    		<span>Already have an account?</span>
    		<a href="<?php echo $this->url('login') ?>">Sign in here</a>.
    	</div>
    </div>
    
    
</div>